"""Run unchanged source-owned Qbrain process regressions on an explicit binary.

This driver records exact subprocess/log identity; it does not replace assertions
inside existing tests. All data generated by the tests is disposable synthetic data.
"""
from __future__ import annotations
import argparse,hashlib,json,os,subprocess,sys
from pathlib import Path


def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument('--binary',type=Path,required=True);p.add_argument('--baseline',type=Path,required=True)
    p.add_argument('--output',type=Path,required=True);a=p.parse_args()
    a.binary=a.binary.resolve(strict=True);a.baseline=a.baseline.resolve(strict=True)
    out=a.output.resolve();out.mkdir(parents=True,exist_ok=False)
    source=Path(__file__).resolve().parents[1];records=[]
    env={k:v for k,v in os.environ.items() if not k.upper().startswith(('QBRAIN','OPENAI','ANTHROPIC'))}
    env.update(PYTHONIOENCODING='utf-8',PYTHONDONTWRITEBYTECODE='1')
    def run(name,args,optimized=False):
        command=[sys.executable,*(['-O'] if optimized else []),str(source/'.ci'/args[0]),*map(str,args[1:])]
        with (out/(name+'.log')).open('wb') as f:
            r=subprocess.run(command,cwd=source,env=env,stdout=f,stderr=subprocess.STDOUT,timeout=180)
        log=(out/(name+'.log')).read_bytes()
        records.append({'name':name,'argv':command,'exit':r.returncode,'log_sha256':hashlib.sha256(log).hexdigest()})
        (out/'driver.json').write_text(json.dumps({'binary_sha256':hashlib.sha256(a.binary.read_bytes()).hexdigest(),
            'baseline_sha256':hashlib.sha256(a.baseline.read_bytes()).hexdigest(),'steps':records},indent=2)+'\n')
        if r.returncode:raise RuntimeError('regression failed: '+name)
    b=a.binary
    run('batches',['test_usage_batches.py','--binary',b,'--output',out/'batches'])
    run('batches-readback',['check_usage_batches.py','--directory',out/'batches','--binary',b,'--test',source/'.ci/test_usage_batches.py','--negatives'])
    run('integrity',['test_receipt_integrity.py','--binary',b,'--baseline',a.baseline,'--output',out/'integrity'])
    run('integrity-readback',['check_receipt_integrity.py','--directory',out/'integrity','--binary',b,'--baseline',a.baseline,
        '--test',source/'.ci/test_receipt_integrity.py','--negative-tests'])
    run('boundary',['test_receipt_integrity_boundary.py','--binary',b,'--output',out/'boundary'])
    run('usage',['test_fact_usage.py','--binary',b,'--report',out/'usage.json'])
    run('usage-readback',['check_fact_usage_report.py','--report',out/'usage.json','--binary',b,'--test',source/'.ci/test_fact_usage.py'])
    run('pages',['test_fact_usage_pages.py','--binary',b,'--report',out/'pages.json','--raw-dir',out/'page-raw'])
    run('pages-readback',['check_fact_usage_pages_report.py','--report',out/'pages.json','--binary',b,
        '--test',source/'.ci/test_fact_usage_pages.py','--raw-dir',out/'page-raw','--negative-tests'])
    for name in ('test_fact_process','test_context_process','test_multiterm_process','test_named_arguments',
                 'test_search_arguments','test_hook_fact_process','test_lifecycle_batch_process'):
        run(name,[name+'.py','--binary',b,'--report',out/(name+'.json')])
    for name in ('test_memory_cycle','test_mcp_boundaries'):
        run(name,[name+'.py','--binary',b])
    print(json.dumps({'result':'RETAINED_PROCESS_GATES_PASSED','process_suites':14,'steps':len(records),
        'real_client_verified':False}))

if __name__=='__main__':main()
